/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExplorerBreadcrumb: typeof import('./src/components/FileExplorer/ExplorerBreadcrumb.vue')['default']
    ExplorerContextMenu: typeof import('./src/components/FileExplorer/ExplorerContextMenu.vue')['default']
    ExplorerStatusbar: typeof import('./src/components/FileExplorer/ExplorerStatusbar.vue')['default']
    ExplorerToolbar: typeof import('./src/components/FileExplorer/ExplorerToolbar.vue')['default']
    ExplorerView: typeof import('./src/components/FileExplorer/ExplorerView.vue')['default']
    FileExplorer: typeof import('./src/components/FileExplorer/FileExplorer.vue')['default']
    FileItemView: typeof import('./src/components/FileExplorer/FileItemView.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEl: typeof import('naive-ui')['NEl']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
  }
}

// For TSX support
declare global {
  const ExplorerBreadcrumb: typeof import('./src/components/FileExplorer/ExplorerBreadcrumb.vue')['default']
  const ExplorerContextMenu: typeof import('./src/components/FileExplorer/ExplorerContextMenu.vue')['default']
  const ExplorerStatusbar: typeof import('./src/components/FileExplorer/ExplorerStatusbar.vue')['default']
  const ExplorerToolbar: typeof import('./src/components/FileExplorer/ExplorerToolbar.vue')['default']
  const ExplorerView: typeof import('./src/components/FileExplorer/ExplorerView.vue')['default']
  const FileExplorer: typeof import('./src/components/FileExplorer/FileExplorer.vue')['default']
  const FileItemView: typeof import('./src/components/FileExplorer/FileItemView.vue')['default']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDialogProvider: typeof import('naive-ui')['NDialogProvider']
  const NEl: typeof import('naive-ui')['NEl']
  const NInput: typeof import('naive-ui')['NInput']
  const NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NModal: typeof import('naive-ui')['NModal']
  const NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
}